export const BOARD_OF_MANAGEMENT_REQUEST = "BOARD_OF_MANAGEMENT_REQUEST";
export const BOARD_OF_MANAGEMENT_SUCCESS = "BOARD_OF_MANAGEMENT_SUCCESS";
export const BOARD_OF_MANAGEMENT_FAIL = "BOARD_OF_MANAGEMENT_FAIL";
