export const EVENT_LIST_REQUEST = "EVENT_LIST_REQUEST"
export const EVENT_LIST_SUCCESS= "EVENT_LIST_SUCCESS"
export const EVENT_LIST_FAIL = "EVENT_LIST_FAIL"

export const EVENT_DETAIL_REQUEST = "EVENT_DETAIL_REQUEST"
export const EVENT_DETAIL_SUCCESS = "EVENT_DETAIL_SUCCESS"
export const EVENT_DETAIL_FAIL = "EVENT_DETAIL_FAIL"