export const LANDING_PAGE_LATEST_EVENT_REQUEST =
  "LANDING_PAGE_LATEST_EVENT_REQUEST";
export const LANDING_PAGE_LATEST_EVENT_SUCCESS =
  "LANDING_PAGE_LATEST_EVENT_SUCCESS";
export const LANDING_PAGE_LATEST_EVENT_FAIL = "LANDING_PAGE_LATEST_EVENT_FAIL";

export const LANDING_PAGE_TESTIMONIAL_REQUEST = "TESTIMONIAL_REQUEST";
export const LANDING_PAGE_TESTIMONIAL_SUCCESS = "TESTIMONIAL_SUCCESS";
export const LANDING_PAGE_TESTIMONIAL_FAIL = "TESTIMONIAL_FAIL";

export const LANDING_PAGE_ALL_SCHOOL_REQUEST = "LANDING_PAGE_SCHOOL_REQUEST";
export const LANDING_PAGE_ALL_SCHOOL_SUCCESS = "LANDING_PAGE_SCHOOL_SUCCESS";
export const LANDING_PAGE_ALL_SCHOOL_FAIL = "LANDING_PAGE_SCHOOL_SUCCESS";

export const LANDING_PAGE_ABOUT_REQUEST = "LANDING_PAGE_ABOUT_REQUEST";
export const LANDING_PAGE_ABOUT_SUCCESS = "LANDING_PAGE_ABOUT_SUCCESS";
export const LANDING_PAGE_ABOUT_FAIL = "   LANDING_PAGE_ABOUT_FAIL";

export const LANDING_PAGE_FEATURE_REQUEST = "LANDING_PAGE_FEATURE_REQUEST";
export const LANDING_PAGE_FEATURE_SUCCESS = "LANDING_PAGE_FEATURE_SUCCESS";
export const LANDING_PAGE_FEATURE_FAIL = "   LANDING_PAGE_FEATURE_FAIL";


export const LANDING_PAGE_GALLERY_REQUEST = "LANDING_PAGE_GALLERY_REQUEST";
export const LANDING_PAGE_GALLERY_SUCCESS = "LANDING_PAGE_GALLERY_SUCCESS";
export const LANDING_PAGE_GALLERY_FAIL = "   LANDING_PAGE_GALLERY_FAIL";
