export const SCHOOL_LIST_REQUEST = "SCHOOL_LIST_REQUEST";
export const SCHOOL_LIST_SUCCESS = "SCHOOL_LIST_SUCCESS";
export const SCHOOL_LIST_FAIL = "SCHOOL_LIST_FAIL";

export const SCHOOL_DETAIL_REQUEST = "SCHOOL_DETAIL_REQUEST";
export const SCHOOL_DETAIL_SUCCESS = "SCHOOL_DETAIL_SUCCESS";
export const SCHOOL_DETAIL_FAIL = "SCHOOL_DETAIL_FAIL";

export const SCHOOL_ABOUT_US_REQUEST = "SCHOOL_ABOUT_US_REQUEST";
export const SCHOOL_ABOUT_US_SUCCESS = "SCHOOL_ABOUT_US_SUCCESS";
export const SCHOOL_ABOUT_US_FAIL = "SCHOOL_ABOUT_US_FAIL";


export const SCHOOL_ADMISSION_REQUEST = "SCHOOL_ADMISSION_REQUEST";
export const SCHOOL_ADMISSION_SUCCESS = "SCHOOL_ADMISSION_SUCCESS";
export const SCHOOL_ADMISSION_FAIL = "SCHOOL_ADMISSION_FAIL";